title: bigDoodR Things
description: These are some of the things I like
author: bigDoodR
url: https://bigdoodr.github.io

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
#email: "not@telling.com"
#twitter_username: "twitteruser"
github_username: "bigdoodr"
linkedin_username: "casey-scruggs-467147245"
mastodon_username: "https://mastodon.social/@bigdoodr"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

social-links:
#  Resume:          /resume
  LinkedIn:        https://linkedin.com/in/casey-scruggs-467147245
  Mastodon:        https://mastodon.social/@bigdoodr

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
nav:
  - title: Me
    children:
      - title: About
        url: /about.html
      - title: Resume
        url: /resume.html
      - title: /guy
        url: /guy/
      - title: /interests
        url: /interests/
      - title: /canon
        url: /canon/
      - title: /now
        url: /now/
      - title: Blog
        url: /archive
      - divider: true
        label: "Site & Contact"
      - title: /hello
        url: /hello/
      - title: /why
        url: /why/
  - title: Talks
    children:
      - title: Adopting an Active Update Cycle
        url: /2024/07/12/macpres/
      - title: "Let's Build Something with swiftDialog"
        url: /2025/07/18/macpres/
      - title: "Stop Tracking Me! Tips for Enhancing Online Privacy"
        url: /2026/01/15/wkuprodevday/
  - title: Apps
    url: /apps/
  - title: Slashes
    url: /slashes/
    children:
      - title: /bookmarks
        url: /bookmarks
      - title: /podroll
        url: /podroll/
      - title: /shoebox
        url: /shoebox/
      - title: /top4
        url: /top4/
      - title: View all slashes →
        url: /slashes/


plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags: Other

exclude:
  - "*.sh"


# sass:
#   sass_dir: _sass
#   style: compressed # Optional, compresses the output CSS
